"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export const partnerLanguages = [
  { code: "th", label: "ไทย", shortLabel: "TH", locale: "th-TH" },
  { code: "en", label: "English", shortLabel: "EN", locale: "en-US" },
  { code: "zh", label: "中文", shortLabel: "中文", locale: "zh-CN" },
];

const defaultLanguage = "th";
const storageKey = "partner_language";

const translations = {
  th: {
    "language.label": "ภาษา",
    "language.select": "เลือกภาษา",
    "common.loading": "กำลังโหลดข้อมูล...",
    "common.today": "วันนี้",
    "common.days": "{count} วัน",
    "common.cancel": "ยกเลิก",
    "common.close": "ปิด",
    "common.free": "ฟรี",
    "common.paid": "เสียเงิน",
    "common.details": "รายละเอียด",
    "common.noThaiTitle": "ไม่มีชื่อภาษาไทย",
    "common.noEnglishTitle": "ไม่มีชื่อภาษาอังกฤษ",
    "common.noChineseTitle": "ไม่มีชื่อภาษาจีน",
    "common.seriesPoster": "โปสเตอร์ซีรีส์",
    "login.checkingSession": "กำลังตรวจสอบสถานะการเข้าสู่ระบบ...",
    "login.brandTopline": "Content Producer Portal",
    "login.analyticsLabel": "Partner analytics",
    "login.headline": "Track how your films perform on Klickshot.",
    "login.copy": "A focused workspace for content producers to review title performance, view trends, and monitor audience response.",
    "login.formTitle": "ระบบผู้ผลิตคอนเทนต์",
    "login.username": "ชื่อผู้ใช้งาน",
    "login.usernamePlaceholder": "กรอกชื่อผู้ใช้งาน",
    "login.password": "รหัสผ่าน",
    "login.passwordPlaceholder": "กรอกรหัสผ่าน",
    "login.remember": "จดจำการเข้าสู่ระบบ",
    "login.submit": "เข้าสู่ระบบ",
    "login.submitting": "กำลังเข้าสู่ระบบ...",
    "login.showPassword": "แสดงรหัสผ่าน",
    "login.hidePassword": "ซ่อนรหัสผ่าน",
    "login.missingCredentials": "กรุณากรอกชื่อผู้ใช้งานและรหัสผ่าน",
    "login.failed": "ไม่สามารถเข้าสู่ระบบได้",
    "login.support": "หากลืมรหัสผ่านหรือยังไม่มีบัญชี กรุณาติดต่อ",
    "nav.dashboard": "ภาพรวม",
    "nav.series": "ซีรีส์ของฉัน",
    "nav.feedback": "ข้อเสนอแนะ",
    "nav.billing": "สรุปรอบบิล",
    "nav.menu": "เมนู Partner",
    "nav.mobileMenu": "เมนู Partner บนมือถือ",
    "nav.openMenu": "เปิดเมนู",
    "nav.closeMenu": "ปิดเมนู",
    "shell.signedInAs": "เข้าสู่ระบบในนาม",
    "shell.logout": "ออกจากระบบ",
    "shell.logoutConfirmKicker": "ยืนยันการออกจากระบบ",
    "shell.logoutConfirmTitle": "ต้องการออกจากระบบใช่ไหม?",
    "shell.logoutConfirmCopy": "เมื่อออกจากระบบแล้ว คุณต้องเข้าสู่ระบบใหม่เพื่อกลับมาจัดการข้อมูล Partner",
    "shell.loggingOut": "กำลังออกจากระบบ...",
    "password.accountKicker": "จัดการบัญชี Partner",
    "password.title": "เปลี่ยนรหัสผ่าน",
    "password.copy": "เปลี่ยนรหัสผ่านของ @{username} โดยกรอกรหัสผ่านปัจจุบันเพื่อยืนยันตัวตนก่อนบันทึก",
    "password.current": "รหัสผ่านปัจจุบัน",
    "password.new": "รหัสผ่านใหม่",
    "password.confirm": "ยืนยันรหัสผ่านใหม่",
    "password.save": "บันทึกรหัสผ่าน",
    "password.saving": "กำลังบันทึก...",
    "password.showCurrent": "แสดงรหัสผ่านปัจจุบัน",
    "password.hideCurrent": "ซ่อนรหัสผ่านปัจจุบัน",
    "password.showNew": "แสดงรหัสผ่านใหม่",
    "password.hideNew": "ซ่อนรหัสผ่านใหม่",
    "password.showConfirm": "แสดงรหัสผ่านยืนยัน",
    "password.hideConfirm": "ซ่อนรหัสผ่านยืนยัน",
    "password.missing": "กรุณากรอกข้อมูลให้ครบทุกช่อง",
    "password.noSpaces": "รหัสผ่านใหม่ต้องไม่มีช่องว่าง",
    "password.tooShort": "รหัสผ่านใหม่ต้องมีอย่างน้อย 6 ตัวอักษร",
    "password.mismatch": "รหัสผ่านใหม่และการยืนยันรหัสผ่านไม่ตรงกัน",
    "password.failed": "ไม่สามารถเปลี่ยนรหัสผ่านได้",
    "password.successTitle": "เปลี่ยนรหัสผ่านสำเร็จ",
    "password.successMessage": "รหัสผ่าน Partner ถูกอัปเดตเรียบร้อยแล้ว",
    "dashboard.title": "ภาพรวมผลงาน",
    "dashboard.copy": "ติดตามยอดดูรายวันของผลงาน แยกตอนฟรีและตอนเสียเงิน ตามข้อมูลจริงของพาร์ทเนอร์",
    "dashboard.summaryLabel": "สรุปยอดดู",
    "dashboard.allPartners": "รวมทุกพาร์ทเนอร์",
    "dashboard.thisPartner": "พาร์ทเนอร์นี้",
    "dashboard.totalViews": "ยอดดูทั้งหมด",
    "dashboard.freePaid": "ฟรี + เสียเงิน",
    "dashboard.ofThisPartner": "ของพาร์ทเนอร์นี้",
    "dashboard.graphKicker": "Streaming graph",
    "dashboard.graphTitle": "กราฟการสตรีมมิ่ง",
    "dashboard.dateRange": "เลือกช่วงวันที่",
    "dashboard.tooltipDate": "วันที่ {date}",
    "dashboard.chartLoadError": "ไม่สามารถดึงข้อมูลกราฟได้",
    "dashboard.chartConnectError": "ไม่สามารถเชื่อมต่อข้อมูลกราฟได้",
    "dashboard.yAxisEpisodes": "จำนวนตอน",
    "series.title": "ซีรีส์ของฉัน",
    "series.copy": "ดูยอดของพาร์ทเนอร์นี้ แยกฟรีและเสียเงินตามช่วงเวลาที่เลือก",
    "series.totalSeries": "ซีรีส์ทั้งหมด",
    "series.total": "ยอดรวม",
    "series.thisSeries": "ของเรื่องนี้",
    "series.dateRange": "เลือกช่วงเวลา",
    "series.loadError": "ไม่สามารถดึงข้อมูลซีรีส์ได้",
    "series.connectError": "ไม่สามารถเชื่อมต่อข้อมูลซีรีส์ได้",
    "series.empty": "ยังไม่มีซีรีส์ในช่วงเวลานี้",
    "series.detailLoadError": "ไม่สามารถดึงข้อมูลรายละเอียดซีรีส์ได้",
    "series.detailConnectError": "ไม่สามารถเชื่อมต่อข้อมูลรายละเอียดซีรีส์ได้",
    "series.detailTitle": "รายละเอียดซีรีส์",
    "series.closeDetails": "ปิดรายละเอียด",
    "series.episodeViewsKicker": "Episode views",
    "series.episodeAnalyticsKicker": "Episode analytics",
    "series.episodeViewsTitle": "ยอดรับชมรายตอน",
    "series.episodeEmpty": "ยังไม่มีข้อมูลรายตอนในช่วงเวลานี้",
    "series.episodeThisViews": "ยอดดูตอนนี้",
    "series.freeEpisodeSuffix": " (ฟรี)",
    "series.freeAreaLegend": "แถบเขียว = ตอนฟรี",
    "feedback.kicker": "Partner feedback",
    "feedback.title": "Feedback / ข้อเสนอแนะ",
    "feedback.copy": "ส่งคำติชม ข้อเสนอแนะ หรือแจ้งปัญหาการใช้งาน Partner Portal ให้ทีม Klickshot",
    "feedback.introKicker": "ส่งข้อความถึงทีมงาน",
    "feedback.introTitle": "ช่วยให้เราปรับ Partner Portal ให้ใช้งานได้ดีขึ้น",
    "feedback.introCopy": "กรอกอีเมลติดต่อกลับ และเล่ารายละเอียดให้ชัดเจน ระบบจะแนบข้อมูลบัญชีพาร์ทเนอร์ของคุณให้อัตโนมัติ",
    "feedback.noteTitle": "ข้อมูลที่ส่งจะถูกจัดเก็บเป็น ticket",
    "feedback.noteCopy": "ทีมงานจะใช้เพื่อตรวจสอบปัญหาและพัฒนาระบบ Partner Portal",
    "feedback.email": "อีเมลติดต่อกลับ",
    "feedback.message": "ข้อความ",
    "feedback.messagePlaceholder": "พิมพ์คำติชม ข้อเสนอแนะ หรือปัญหาที่พบได้ที่นี่",
    "feedback.submit": "ส่งข้อความ",
    "feedback.submitting": "กำลังส่ง...",
    "feedback.failed": "ไม่สามารถส่งข้อความได้",
    "feedback.successTitle": "ส่งข้อความแล้ว",
    "feedback.successMessage": "ทีมงานได้รับข้อความของคุณเรียบร้อยแล้ว",
    "billing.title": "รายงานรอบบิล",
    "billing.copy": "ตรวจสอบยอดรายได้ที่ได้รับ ยอดดูรวม และรายละเอียดแยกตามซีรีย์",
    "billing.sentReports": "รายงานที่ส่งแล้ว",
    "billing.totalRevenue": "รายได้รวม",
    "billing.freeEpisodeViews": "ยอดดูตอนฟรี",
    "billing.paidEpisodeViews": "ยอดดูตอนเสียเงิน",
    "billing.loadError": "ไม่สามารถโหลดรายงานรอบบิลได้",
    "billing.connectError": "ไม่สามารถเชื่อมต่อข้อมูลรอบบิลได้",
    "billing.loading": "กำลังโหลดรายงานรอบบิล...",
    "billing.empty": "ยังไม่มีรายงานรอบบิลที่ถูกส่งมา",
    "billing.sentOn": "ส่งเมื่อ {date}",
    "billing.viewDetails": "ดูรายละเอียด",
    "billing.revenueReceived": "รายได้ที่ได้รับ",
    "billing.freeEpisodes": "ตอนฟรี",
    "billing.paidEpisodes": "ตอนเสียเงิน",
    "billing.adjustedViews": "ยอดดูถ่วงน้ำหนัก",
    "billing.detailKicker": "รายละเอียดรอบบิล",
    "billing.detailTitle": "รายละเอียดรอบบิล",
    "billing.detailCopy": "ตรวจสอบรายละเอียดรอบบิลและรายการซีรีย์",
    "billing.detailLoading": "กำลังโหลดรายละเอียดรอบบิล...",
    "billing.detailLoadError": "ไม่สามารถโหลดรายละเอียดรอบบิลได้",
    "billing.detailConnectError": "ไม่สามารถเชื่อมต่อข้อมูลรายละเอียดรอบบิลได้",
    "billing.detailNotFound": "ไม่พบรายละเอียดรอบบิลนี้",
    "billing.backToBilling": "กลับไปสรุปรอบบิล",
    "billing.closeDetails": "ปิดรายละเอียดรายงาน",
    "billing.series": "ซีรีย์",
    "billing.amount": "ยอดเงิน",
    "billing.emptySeries": "ไม่มีข้อมูลซีรีย์ในรอบบิลนี้",
    "billing.seriesFallback": "ซีรีย์ #{id}",
  },
  en: {
    "language.label": "Language",
    "language.select": "Select language",
    "common.loading": "Loading data...",
    "common.today": "Today",
    "common.days": "{count} days",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.free": "Free",
    "common.paid": "Paid",
    "common.details": "Details",
    "common.noThaiTitle": "No Thai title",
    "common.noEnglishTitle": "No English title",
    "common.noChineseTitle": "No Chinese title",
    "common.seriesPoster": "Series poster",
    "login.checkingSession": "Checking sign-in status...",
    "login.brandTopline": "Content Producer Portal",
    "login.analyticsLabel": "Partner analytics",
    "login.headline": "Track how your films perform on Klickshot.",
    "login.copy": "A focused workspace for content producers to review title performance, view trends, and monitor audience response.",
    "login.formTitle": "Content Producer Portal",
    "login.username": "Username",
    "login.usernamePlaceholder": "Enter username",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter password",
    "login.remember": "Remember me",
    "login.submit": "Sign in",
    "login.submitting": "Signing in...",
    "login.showPassword": "Show password",
    "login.hidePassword": "Hide password",
    "login.missingCredentials": "Please enter your username and password",
    "login.failed": "Unable to sign in",
    "login.support": "If you forgot your password or do not have an account, please contact",
    "nav.dashboard": "Dashboard",
    "nav.series": "My Series",
    "nav.feedback": "Feedback",
    "nav.billing": "Billing",
    "nav.menu": "Partner menu",
    "nav.mobileMenu": "Mobile Partner menu",
    "nav.openMenu": "Open menu",
    "nav.closeMenu": "Close menu",
    "shell.signedInAs": "Signed in as",
    "shell.logout": "Log out",
    "shell.logoutConfirmKicker": "Confirm logout",
    "shell.logoutConfirmTitle": "Do you want to log out?",
    "shell.logoutConfirmCopy": "After logging out, you will need to sign in again to manage Partner data.",
    "shell.loggingOut": "Logging out...",
    "password.accountKicker": "Partner account",
    "password.title": "Change password",
    "password.copy": "Change the password for @{username}. Enter your current password to verify your identity before saving.",
    "password.current": "Current password",
    "password.new": "New password",
    "password.confirm": "Confirm new password",
    "password.save": "Save password",
    "password.saving": "Saving...",
    "password.showCurrent": "Show current password",
    "password.hideCurrent": "Hide current password",
    "password.showNew": "Show new password",
    "password.hideNew": "Hide new password",
    "password.showConfirm": "Show confirmation password",
    "password.hideConfirm": "Hide confirmation password",
    "password.missing": "Please complete every field",
    "password.noSpaces": "The new password cannot contain spaces",
    "password.tooShort": "The new password must be at least 6 characters",
    "password.mismatch": "The new password and confirmation do not match",
    "password.failed": "Unable to change password",
    "password.successTitle": "Password changed",
    "password.successMessage": "Your Partner password has been updated.",
    "dashboard.title": "Performance Overview",
    "dashboard.copy": "Track daily views for your titles, split by free and paid episodes using real partner data.",
    "dashboard.summaryLabel": "View summary",
    "dashboard.allPartners": "All partners",
    "dashboard.thisPartner": "This partner",
    "dashboard.totalViews": "Total views",
    "dashboard.freePaid": "Free + paid",
    "dashboard.ofThisPartner": "For this partner",
    "dashboard.graphKicker": "Streaming graph",
    "dashboard.graphTitle": "Streaming Graph",
    "dashboard.dateRange": "Select date range",
    "dashboard.tooltipDate": "Date {date}",
    "dashboard.chartLoadError": "Unable to load chart data",
    "dashboard.chartConnectError": "Unable to connect to chart data",
    "dashboard.yAxisEpisodes": "Episodes",
    "series.title": "My Series",
    "series.copy": "View this partner's performance, split by free and paid episodes for the selected range.",
    "series.totalSeries": "Total series",
    "series.total": "Total",
    "series.thisSeries": "This title",
    "series.dateRange": "Select range",
    "series.loadError": "Unable to load series data",
    "series.connectError": "Unable to connect to series data",
    "series.empty": "No series in this period",
    "series.detailLoadError": "Unable to load series details",
    "series.detailConnectError": "Unable to connect to series details",
    "series.detailTitle": "Series details",
    "series.closeDetails": "Close details",
    "series.episodeViewsKicker": "Episode views",
    "series.episodeAnalyticsKicker": "Episode analytics",
    "series.episodeViewsTitle": "Episode Views",
    "series.episodeEmpty": "No episode data in this period",
    "series.episodeThisViews": "Views for this episode",
    "series.freeEpisodeSuffix": " (free)",
    "series.freeAreaLegend": "Green band = free episodes",
    "feedback.kicker": "Partner feedback",
    "feedback.title": "Feedback",
    "feedback.copy": "Send comments, suggestions, or Partner Portal issues to the Klickshot team.",
    "feedback.introKicker": "Message the team",
    "feedback.introTitle": "Help us improve the Partner Portal",
    "feedback.introCopy": "Enter a contact email and describe the details clearly. Your partner account information will be attached automatically.",
    "feedback.noteTitle": "Submitted information will be stored as a ticket",
    "feedback.noteCopy": "The team will use it to investigate issues and improve the Partner Portal.",
    "feedback.email": "Contact email",
    "feedback.message": "Message",
    "feedback.messagePlaceholder": "Type feedback, suggestions, or issues here",
    "feedback.submit": "Send message",
    "feedback.submitting": "Sending...",
    "feedback.failed": "Unable to send message",
    "feedback.successTitle": "Message sent",
    "feedback.successMessage": "The team has received your message.",
    "billing.title": "Billing Reports",
    "billing.copy": "Review received revenue, total views, and details by series.",
    "billing.sentReports": "Sent reports",
    "billing.totalRevenue": "Total revenue",
    "billing.freeEpisodeViews": "Free episode views",
    "billing.paidEpisodeViews": "Paid episode views",
    "billing.loadError": "Unable to load billing reports",
    "billing.connectError": "Unable to connect to billing data",
    "billing.loading": "Loading billing reports...",
    "billing.empty": "No sent billing reports yet",
    "billing.sentOn": "Sent on {date}",
    "billing.viewDetails": "View details",
    "billing.revenueReceived": "Revenue received",
    "billing.freeEpisodes": "Free episodes",
    "billing.paidEpisodes": "Paid episodes",
    "billing.adjustedViews": "Weighted views",
    "billing.detailKicker": "Billing details",
    "billing.detailTitle": "Billing Details",
    "billing.detailCopy": "Review billing details and series breakdown.",
    "billing.detailLoading": "Loading billing details...",
    "billing.detailLoadError": "Unable to load billing details",
    "billing.detailConnectError": "Unable to connect to billing details",
    "billing.detailNotFound": "Billing report details were not found",
    "billing.backToBilling": "Back to Billing",
    "billing.closeDetails": "Close report details",
    "billing.series": "Series",
    "billing.amount": "Amount",
    "billing.emptySeries": "No series data in this billing report",
    "billing.seriesFallback": "Series #{id}",
  },
  zh: {
    "language.label": "语言",
    "language.select": "选择语言",
    "common.loading": "正在加载数据...",
    "common.today": "今天",
    "common.days": "{count} 天",
    "common.cancel": "取消",
    "common.close": "关闭",
    "common.free": "免费",
    "common.paid": "付费",
    "common.details": "详情",
    "common.noThaiTitle": "暂无泰文标题",
    "common.noEnglishTitle": "暂无英文标题",
    "common.noChineseTitle": "暂无中文标题",
    "common.seriesPoster": "剧集海报",
    "login.checkingSession": "正在检查登录状态...",
    "login.brandTopline": "内容制作方平台",
    "login.analyticsLabel": "合作方数据",
    "login.headline": "查看你的作品在 Klickshot 的表现。",
    "login.copy": "为内容制作方打造的工作区，用于查看作品表现、趋势和观众反馈。",
    "login.formTitle": "内容制作方平台",
    "login.username": "用户名",
    "login.usernamePlaceholder": "输入用户名",
    "login.password": "密码",
    "login.passwordPlaceholder": "输入密码",
    "login.remember": "记住登录",
    "login.submit": "登录",
    "login.submitting": "正在登录...",
    "login.showPassword": "显示密码",
    "login.hidePassword": "隐藏密码",
    "login.missingCredentials": "请输入用户名和密码",
    "login.failed": "无法登录",
    "login.support": "如果忘记密码或还没有账号，请联系",
    "nav.dashboard": "概览",
    "nav.series": "我的剧集",
    "nav.feedback": "反馈",
    "nav.billing": "账单",
    "nav.menu": "合作方菜单",
    "nav.mobileMenu": "移动端合作方菜单",
    "nav.openMenu": "打开菜单",
    "nav.closeMenu": "关闭菜单",
    "shell.signedInAs": "当前登录",
    "shell.logout": "退出登录",
    "shell.logoutConfirmKicker": "确认退出",
    "shell.logoutConfirmTitle": "确定要退出登录吗？",
    "shell.logoutConfirmCopy": "退出后，你需要重新登录才能继续管理合作方数据。",
    "shell.loggingOut": "正在退出...",
    "password.accountKicker": "合作方账号",
    "password.title": "修改密码",
    "password.copy": "修改 @{username} 的密码。保存前请先输入当前密码以验证身份。",
    "password.current": "当前密码",
    "password.new": "新密码",
    "password.confirm": "确认新密码",
    "password.save": "保存密码",
    "password.saving": "正在保存...",
    "password.showCurrent": "显示当前密码",
    "password.hideCurrent": "隐藏当前密码",
    "password.showNew": "显示新密码",
    "password.hideNew": "隐藏新密码",
    "password.showConfirm": "显示确认密码",
    "password.hideConfirm": "隐藏确认密码",
    "password.missing": "请填写所有字段",
    "password.noSpaces": "新密码不能包含空格",
    "password.tooShort": "新密码至少需要 6 个字符",
    "password.mismatch": "新密码和确认密码不一致",
    "password.failed": "无法修改密码",
    "password.successTitle": "密码已修改",
    "password.successMessage": "合作方密码已更新。",
    "dashboard.title": "作品概览",
    "dashboard.copy": "根据合作方真实数据，按免费和付费剧集查看每日观看量。",
    "dashboard.summaryLabel": "观看摘要",
    "dashboard.allPartners": "所有合作方",
    "dashboard.thisPartner": "当前合作方",
    "dashboard.totalViews": "总观看量",
    "dashboard.freePaid": "免费 + 付费",
    "dashboard.ofThisPartner": "当前合作方",
    "dashboard.graphKicker": "播放图表",
    "dashboard.graphTitle": "播放趋势图",
    "dashboard.dateRange": "选择日期范围",
    "dashboard.tooltipDate": "日期 {date}",
    "dashboard.chartLoadError": "无法加载图表数据",
    "dashboard.chartConnectError": "无法连接图表数据",
    "dashboard.yAxisEpisodes": "剧集数量",
    "series.title": "我的剧集",
    "series.copy": "按所选时间范围查看当前合作方的免费和付费观看表现。",
    "series.totalSeries": "剧集总数",
    "series.total": "总计",
    "series.thisSeries": "本剧集",
    "series.dateRange": "选择时间范围",
    "series.loadError": "无法加载剧集数据",
    "series.connectError": "无法连接剧集数据",
    "series.empty": "此时间范围内暂无剧集",
    "series.detailLoadError": "无法加载剧集详情",
    "series.detailConnectError": "无法连接剧集详情",
    "series.detailTitle": "剧集详情",
    "series.closeDetails": "关闭详情",
    "series.episodeViewsKicker": "单集观看量",
    "series.episodeAnalyticsKicker": "单集分析",
    "series.episodeViewsTitle": "单集观看量",
    "series.episodeEmpty": "此时间范围内暂无单集数据",
    "series.episodeThisViews": "本集观看量",
    "series.freeEpisodeSuffix": "（免费）",
    "series.freeAreaLegend": "绿色区域 = 免费剧集",
    "feedback.kicker": "合作方反馈",
    "feedback.title": "反馈",
    "feedback.copy": "向 Klickshot 团队发送建议、反馈或 Partner Portal 使用问题。",
    "feedback.introKicker": "联系团队",
    "feedback.introTitle": "帮助我们改进 Partner Portal",
    "feedback.introCopy": "请输入联系邮箱，并清楚描述详情。系统会自动附上你的合作方账号信息。",
    "feedback.noteTitle": "提交的信息会保存为 ticket",
    "feedback.noteCopy": "团队会用它来排查问题并改进 Partner Portal。",
    "feedback.email": "联系邮箱",
    "feedback.message": "消息",
    "feedback.messagePlaceholder": "在这里输入反馈、建议或遇到的问题",
    "feedback.submit": "发送消息",
    "feedback.submitting": "正在发送...",
    "feedback.failed": "无法发送消息",
    "feedback.successTitle": "消息已发送",
    "feedback.successMessage": "团队已收到你的消息。",
    "billing.title": "账单报告",
    "billing.copy": "查看已收到收入、总观看量以及按剧集拆分的详情。",
    "billing.sentReports": "已发送报告",
    "billing.totalRevenue": "总收入",
    "billing.freeEpisodeViews": "免费剧集观看量",
    "billing.paidEpisodeViews": "付费剧集观看量",
    "billing.loadError": "无法加载账单报告",
    "billing.connectError": "无法连接账单数据",
    "billing.loading": "正在加载账单报告...",
    "billing.empty": "暂无已发送的账单报告",
    "billing.sentOn": "发送于 {date}",
    "billing.viewDetails": "查看详情",
    "billing.revenueReceived": "已收到收入",
    "billing.freeEpisodes": "免费剧集",
    "billing.paidEpisodes": "付费剧集",
    "billing.adjustedViews": "加权观看量",
    "billing.detailKicker": "账单详情",
    "billing.detailTitle": "账单详情",
    "billing.detailCopy": "查看账单详情和剧集明细。",
    "billing.detailLoading": "正在加载账单详情...",
    "billing.detailLoadError": "无法加载账单详情",
    "billing.detailConnectError": "无法连接账单详情",
    "billing.detailNotFound": "未找到账单详情",
    "billing.backToBilling": "返回账单",
    "billing.closeDetails": "关闭报告详情",
    "billing.series": "剧集",
    "billing.amount": "金额",
    "billing.emptySeries": "此账单报告暂无剧集数据",
    "billing.seriesFallback": "剧集 #{id}",
  },
};

const PartnerLanguageContext = createContext(null);

function interpolate(value, params) {
  if (!params) return value;

  return value.replace(/\{(\w+)\}/g, (match, key) => {
    if (params[key] === undefined || params[key] === null) return match;
    return String(params[key]);
  });
}

function getLanguageOption(language) {
  return partnerLanguages.find((option) => option.code === language) || partnerLanguages[0];
}

export function PartnerLanguageProvider({ children }) {
  const [language, setLanguageState] = useState(defaultLanguage);

  useEffect(() => {
    const storedLanguage = window.localStorage.getItem(storageKey);
    if (translations[storedLanguage]) {
      setLanguageState(storedLanguage);
    }
  }, []);

  const setLanguage = (nextLanguage) => {
    if (!translations[nextLanguage]) return;

    setLanguageState(nextLanguage);
    window.localStorage.setItem(storageKey, nextLanguage);
    document.documentElement.lang = nextLanguage;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => {
    const option = getLanguageOption(language);

    return {
      language,
      languageOption: option,
      languages: partnerLanguages,
      locale: option.locale,
      setLanguage,
      t(key, params) {
        const value = translations[language]?.[key] ?? translations[defaultLanguage]?.[key] ?? key;
        return interpolate(value, params);
      },
    };
  }, [language]);

  return (
    <PartnerLanguageContext.Provider value={value}>
      {children}
    </PartnerLanguageContext.Provider>
  );
}

export function usePartnerLanguage() {
  const context = useContext(PartnerLanguageContext);
  if (!context) {
    throw new Error("usePartnerLanguage must be used within PartnerLanguageProvider");
  }

  return context;
}

export function LanguageSwitcher({ className = "" }) {
  const { language, languages, setLanguage, t } = usePartnerLanguage();

  return (
    <label className={`partner-language-switcher ${className}`}>
      <span>{t("language.label")}</span>
      <select
        value={language}
        onChange={(event) => setLanguage(event.target.value)}
        aria-label={t("language.select")}
      >
        {languages.map((option) => (
          <option key={option.code} value={option.code}>
            {option.label}
          </option>
        ))}
      </select>
    </label>
  );
}
